### ISSUE TITLE
Ignored words not working on whispers

### ISSUE THREAD

**Issue by Anothersignup** [funkydude/BadBoy#137]
### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Assuming you're talking about BadBoy_CCleaner, this is correct. It only filters public chat which is intentional. If someone is directly whispering something of objection to you, report them, or use BadBoy_Levels to control who can whisper you.

It's possible in future the addon will let you choose what chat types to filter, but this isn't possible right now.
