### ISSUE TITLE
Not working properly with Elvui classic

### ISSUE THREAD

**Issue by Zekler** [funkydude/BadBoy#143]
## Describe the problem
Badboy_Ccleaner is overwriting the ui for my chat input window when i'm using Elvui.

### What steps will reproduce the problem?

1.  having Elvui
2.  Installing Badboy + badboy_ccleaner
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Orignial Layout.
![image](https://user-images.githubusercontent.com/26659628/117569816-c2e99300-b0c7-11eb-9cea-aff570e8439e.png)
New Layout.
![image](https://user-images.githubusercontent.com/26659628/117569886-0a701f00-b0c8-11eb-9a24-ad25d2da70c9.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
9.0.2

**Comment by funkydude** [comment]
BadBoy_CCleaner adds chat filters and has nothing to do with UI elements, it will not be the cause of UI changes.
Also your screenshots do not make it clear what the problem is. The first screenshot looks like it was taken without ElvUI, the second screenshot looks like it was taken with ElvUI. So it's not clear to me what role CCleaner has here.
