### ISSUE TITLE
Not important, just want my question answered.

### ISSUE THREAD

**Issue by xyzforgottenme** [funkydude/BadBoy#89]
**DO NOT POST SPAM HERE**
Post text (not screenshots) on pastebin.com and link it here.
Use the title "missed spam".
Does BadBoy monitor /LookingForGroup (Yes or No?)

1. I am not talking about /Guild
2. Guild spam was just an example, considering I believe the addons are most likely similar in regards to what channels are monitored.
3. The channel I am talking it used heavily on larger realms, other types of spam are in abundance.
4. I simply am asking does BadBoy monitor the chat channel and report relevant spam. 
5. Yes, I have checked you can report people on /LookingForGroup for spamming/language and all the etc. 
6. No I am not talking about the LFG tool, I am talking about the /LookingForGroup Channel.

**Comment by funkydude** [comment]
As this is the third issue you have opened about this instead of replying in the previous ones, you are now banned for 7 days for spamming my project.

1. /Guild isn't a public channel, it's a private channel, so it won't be scanned. I didn't once mention /Guild, I don't understand your obsession with this. Maybe you are not English or something.
2. As already stated, all `public` chat is monitored.
3. Makes no difference how popular it is.
4. It monitors the channel for **reportable** spam like gold/boosts, guild advertising is not reportable spam.
5. Yes...
6. I didn't once mention the LFG tool in any of my posts.
