### ISSUE TITLE
Unexpected GUID requested by an addon

### ISSUE THREAD

**Issue by F5in** [funkydude/BadBoy#90]
https://pastebin.com/jznHpr51

There is a bugsack error I've been getting. Notice the 47x. Sometimes it has multiple GUIDs with varying amounts of x next to them. It triggers whenever I load into a character. Not sure if it's a BugSack issue or something to do with ElvUI but I find it extremely hard to get help from ElvUI for specific things like this because they have so many things they're working on all the time.

**Comment by funkydude** [comment]
Caused by one of your addons passing invalid data to chat filters, most likely ElvUI,

**Comment by F5in** [comment]
Thanks for the reply. I asked ElvUI about it and they had me disable and re-enable addons until I had the minimum amount of addons and still had an error. If I have ElvUI, ElvUI_Config, and BadBoy enabled, I get no errors, but as soon as I enable BadBoy_CCleaner I get errors again.

**Comment by funkydude** [comment]
CCleaner uses the API provided by BadBoy. The reason it only errors when you have CCleaner enabled is because CCleaner sources it's data from the chat filters, BadBoy sources its data directly from the events which cannot be tampered with like ElvUI is tampering with the chat filters by passing invalid data to them.
